wip:new code

diff --git a/src/test/tasks.yaml b/src/test/tasks.yaml
--- a/src/test/tasks.yaml
+++ b/src/test/tasks.yaml
@@ -27,196 +27,196 @@ tasks:
       - description: Deploy the test resources
         cmd: "uds zarf package deploy build/zarf-package-uds-core-test-apps-*.zst --confirm --no-progress"
 
-      - description: Wait for the admin app to be ready
-        wait:
-          cluster:
-            kind: Deployment
-            name: httpbin
-            namespace: test-admin-app
+  #     - description: Wait for the admin app to be ready
+  #       wait:
+  #         cluster:
+  #           kind: Deployment
+  #           name: httpbin
+  #           namespace: test-admin-app
 
-      - description: Verify admin package CR is ready
-        wait:
-          cluster:
-            kind: Package
-            name: httpbin
-            namespace: test-admin-app
-            condition: "'{.status.phase}'=Ready"
+  #     - description: Verify admin package CR is ready
+  #       wait:
+  #         cluster:
+  #           kind: Package
+  #           name: httpbin
+  #           namespace: test-admin-app
+  #           condition: "'{.status.phase}'=Ready"
 
-      - description: Wait for the tenant app to be ready
-        wait:
-          cluster:
-            kind: Deployment
-            name: http-echo-multi-port
-            namespace: test-tenant-app
+  #     - description: Wait for the tenant app to be ready
+  #       wait:
+  #         cluster:
+  #           kind: Deployment
+  #           name: http-echo-multi-port
+  #           namespace: test-tenant-app
 
-      - description: Verify tenant package CR is ready
-        wait:
-          cluster:
-            kind: Package
-            name: test-tenant-app
-            namespace: test-tenant-app
-            condition: "'{.status.phase}'=Ready"
+  #     - description: Verify tenant package CR is ready
+  #       wait:
+  #         cluster:
+  #           kind: Package
+  #           name: test-tenant-app
+  #           namespace: test-tenant-app
+  #           condition: "'{.status.phase}'=Ready"
 
-      - description: Verify the admin app is accessible
-        wait:
-          network:
-            protocol: https
-            address: demo.admin.uds.dev/status/202
-            code: 202
+  #     - description: Verify the admin app is accessible
+  #       wait:
+  #         network:
+  #           protocol: https
+  #           address: demo.admin.uds.dev/status/202
+  #           code: 202
 
-      - description: Verify the VS Match rules for method regex/uri prefix
-        wait:
-          network:
-            protocol: https
-            address: demo.admin.uds.dev/status/302
-            code: 404
+  #     - description: Verify the VS Match rules for method regex/uri prefix
+  #       wait:
+  #         network:
+  #           protocol: https
+  #           address: demo.admin.uds.dev/status/302
+  #           code: 404
 
-      - description: Verify the VS Match rules for uri exact
-        wait:
-          network:
-            protocol: https
-            address: demo.admin.uds.dev/status/410
-            code: 410
+  #     - description: Verify the VS Match rules for uri exact
+  #       wait:
+  #         network:
+  #           protocol: https
+  #           address: demo.admin.uds.dev/status/410
+  #           code: 410
 
-      - description: Verify the tenant app 8080 is accessible
-        wait:
-          network:
-            protocol: https
-            address: demo-8080.uds.dev
-            code: 200
+  #     - description: Verify the tenant app 8080 is accessible
+  #       wait:
+  #         network:
+  #           protocol: https
+  #           address: demo-8080.uds.dev
+  #           code: 200
 
-      - description: Verify the tenant app 8081 is accessible
-        wait:
-          network:
-            protocol: https
-            address: demo-8081.uds.dev
-            code: 200
+  #     - description: Verify the tenant app 8081 is accessible
+  #       wait:
+  #         network:
+  #           protocol: https
+  #           address: demo-8081.uds.dev
+  #           code: 200
 
-      - description: Verify authservice app package CR is ready
-        wait:
-          cluster:
-            kind: Package
-            name: httpbin-other
-            namespace: authservice-test-app
-            condition: "'{.status.phase}'=Ready"
+  #     - description: Verify authservice app package CR is ready
+  #       wait:
+  #         cluster:
+  #           kind: Package
+  #           name: httpbin-other
+  #           namespace: authservice-test-app
+  #           condition: "'{.status.phase}'=Ready"
 
-      - description: Verify the authservice tenant app is accessible
-        wait:
-          network:
-            protocol: https
-            address: protected.uds.dev
-            code: 200
+  #     - description: Verify the authservice tenant app is accessible
+  #       wait:
+  #         network:
+  #           protocol: https
+  #           address: protected.uds.dev
+  #           code: 200
 
-      - description: Wait for authservice to reload configuration
-        wait:
-          cluster:
-            kind: Deployment
-            name: authservice
-            namespace: authservice
+  #     - description: Wait for authservice to reload configuration
+  #       wait:
+  #         cluster:
+  #           kind: Deployment
+  #           name: authservice
+  #           namespace: authservice
 
-      - description: Verify the authservice tenant app is protected by checking redirect
-        maxRetries: 3
-        cmd: |
-          set -e
-          SSO_REDIRECT=$(uds zarf tools kubectl run curl-test --image=cgr.dev/chainguard/curl:latest -q --restart=Never --rm -i -- -Ls -o /dev/null -w %{url_effective} "https://protected.uds.dev")
+  #     - description: Verify the authservice tenant app is protected by checking redirect
+  #       maxRetries: 3
+  #       cmd: |
+  #         set -e
+  #         SSO_REDIRECT=$(uds zarf tools kubectl run curl-test --image=cgr.dev/chainguard/curl:latest -q --restart=Never --rm -i -- -Ls -o /dev/null -w %{url_effective} "https://protected.uds.dev")
 
-          case "${SSO_REDIRECT}" in
-          "https://sso.uds.dev"*)
-              echo "Protected by authservice"
-              ;;
-          *)
-              # Fallback option if the condition is false
-              echo "App is not protected by authservice"
-              echo $SSO_REDIRECT
-              exit 1
-              ;;
-          esac
+  #         case "${SSO_REDIRECT}" in
+  #         "https://sso.uds.dev"*)
+  #             echo "Protected by authservice"
+  #             ;;
+  #         *)
+  #             # Fallback option if the condition is false
+  #             echo "App is not protected by authservice"
+  #             echo $SSO_REDIRECT
+  #             exit 1
+  #             ;;
+  #         esac
 
-      - description: Verify podinfo is healthy
-        wait:
-          cluster:
-            kind: Pod
-            name: app.kubernetes.io/name=podinfo
-            namespace: podinfo
-            condition: Ready
+  #     - description: Verify podinfo is healthy
+  #       wait:
+  #         cluster:
+  #           kind: Pod
+  #           name: app.kubernetes.io/name=podinfo
+  #           namespace: podinfo
+  #           condition: Ready
 
-      - description: Verify podinfo package CR is ready
-        wait:
-          cluster:
-            kind: Package
-            name: podinfo
-            namespace: podinfo
-            condition: "'{.status.phase}'=Ready"
+  #     - description: Verify podinfo package CR is ready
+  #       wait:
+  #         cluster:
+  #           kind: Package
+  #           name: podinfo
+  #           namespace: podinfo
+  #           condition: "'{.status.phase}'=Ready"
 
-      - description: Verify podinfo podmonitor exists
-        wait:
-          cluster:
-            kind: PodMonitor
-            name: podinfo-podmonitor
-            namespace: podinfo
+  #     - description: Verify podinfo podmonitor exists
+  #       wait:
+  #         cluster:
+  #           kind: PodMonitor
+  #           name: podinfo-podmonitor
+  #           namespace: podinfo
 
-      - description: Validate podinfo servicemonitor exists
-        wait:
-          cluster:
-            kind: ServiceMonitor
-            name: podinfo-svcmonitor
-            namespace: podinfo
+  #     - description: Validate podinfo servicemonitor exists
+  #       wait:
+  #         cluster:
+  #           kind: ServiceMonitor
+  #           name: podinfo-svcmonitor
+  #           namespace: podinfo
 
-      - description: "Wait for Deny All Package 1 to be Ready"
-        wait:
-          cluster:
-            kind: Pod
-            name: app=curl-pkg-deny-all-1
-            namespace: curl-ns-deny-all
-            condition: Ready
+  #     - description: "Wait for Deny All Package 1 to be Ready"
+  #       wait:
+  #         cluster:
+  #           kind: Pod
+  #           name: app=curl-pkg-deny-all-1
+  #           namespace: curl-ns-deny-all
+  #           condition: Ready
 
-      - description: "Wait for Deny All Package 2 to be Ready"
-        wait:
-          cluster:
-            kind: Pod
-            name: app=curl-pkg-deny-all-2
-            namespace: curl-ns-deny-all
-            condition: Ready
+  #     - description: "Wait for Deny All Package 2 to be Ready"
+  #       wait:
+  #         cluster:
+  #           kind: Pod
+  #           name: app=curl-pkg-deny-all-2
+  #           namespace: curl-ns-deny-all
+  #           condition: Ready
 
-      - description: "Wait for Allow All Package to be Ready"
-        wait:
-          cluster:
-            kind: Pod
-            name: app=curl-pkg-allow-all
-            namespace: curl-ns-allow-all
-            condition: Ready
+  #     - description: "Wait for Allow All Package to be Ready"
+  #       wait:
+  #         cluster:
+  #           kind: Pod
+  #           name: app=curl-pkg-allow-all
+  #           namespace: curl-ns-allow-all
+  #           condition: Ready
 
-      - description: "Wait for Remote Namespace Egress Package to be Ready"
-        wait:
-          cluster:
-            kind: Pod
-            name: app=curl-pkg-remote-ns-egress
-            namespace: curl-ns-remote-ns-1
-            condition: Ready
+  #     - description: "Wait for Remote Namespace Egress Package to be Ready"
+  #       wait:
+  #         cluster:
+  #           kind: Pod
+  #           name: app=curl-pkg-remote-ns-egress
+  #           namespace: curl-ns-remote-ns-1
+  #           condition: Ready
 
-      - description: "Wait for Remote Namespace Ingress Package to be Ready"
-        wait:
-          cluster:
-            kind: Pod
-            name: app=curl-pkg-remote-ns-ingress
-            namespace: curl-ns-remote-ns-2
-            condition: Ready
+  #     - description: "Wait for Remote Namespace Ingress Package to be Ready"
+  #       wait:
+  #         cluster:
+  #           kind: Pod
+  #           name: app=curl-pkg-remote-ns-ingress
+  #           namespace: curl-ns-remote-ns-2
+  #           condition: Ready
 
-      - description: "Wait for Kube Api Package to be Ready"
-        wait:
-          cluster:
-            kind: Pod
-            name: app=curl-pkg-kube-api
-            namespace: curl-ns-kube-api
-            condition: Ready
+  #     - description: "Wait for Kube Api Package to be Ready"
+  #       wait:
+  #         cluster:
+  #           kind: Pod
+  #           name: app=curl-pkg-kube-api
+  #           namespace: curl-ns-kube-api
+  #           condition: Ready
 
-      - description: "Wait for Remote Cidr Package to be Ready"
-        wait:
-          cluster:
-            kind: Pod
-            name: app=curl-pkg-remote-cidr
-            namespace: curl-ns-remote-cidr
-            condition: Ready
+  #     - description: "Wait for Remote Cidr Package to be Ready"
+  #       wait:
+  #         cluster:
+  #           kind: Pod
+  #           name: app=curl-pkg-remote-cidr
+  #           namespace: curl-ns-remote-cidr
+  #           condition: Ready
 
   - name: remove
     actions:
