chore: modernize dev workflow w/ mise and hk (#2976)
## Description

This PR moves to using mise to manage the lifecycle of dependency tools.
This includes having users and CI run `mise install` to download and use
pinned version of dev tools. Additionally we swap out husky for hk to
bring core in line with our other repos.

## Related Issue

Fixes CORE-690

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Steps to Validate
- If this PR introduces new functionality to UDS Core or addresses a
bug, please document the steps to test the changes.

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor
Guide](https://github.com/defenseunicorns/uds-core/blob/main/CONTRIBUTING.md)
followed

diff --git a/src/pepr/tasks.yaml b/src/pepr/tasks.yaml
--- a/src/pepr/tasks.yaml
+++ b/src/pepr/tasks.yaml
@@ -65,16 +65,15 @@ tasks:
           darwin: bash
           linux: bash
         cmd: |
-          # check for addlicense bin
-          if [ -x "$HOME/go/bin/addlicense" ]; then
-            echo "addlicense installed in $HOME/go/bin"
+          if command -v addlicense >/dev/null 2>&1; then
+            echo "addlicense installed"
           else
-            echo "Error: addlicense is not installed in $HOME/go/bin" >&2
+            echo "Error: addlicense is not installed" >&2
             exit 1
           fi
-          $HOME/go/bin/addlicense -l "AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial" -s=only -v -c "Defense Unicorns" src/pepr/operator/crd/sources
-          $HOME/go/bin/addlicense -l "AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial" -s=only -v -c "Defense Unicorns" src/pepr/operator/crd/generated
-          $HOME/go/bin/addlicense -l "AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial" -s=only -v -c "Defense Unicorns" src/pepr/uds-cluster-crds/templates
+          addlicense -l "AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial" -s=only -v -c "Defense Unicorns" src/pepr/operator/crd/sources
+          addlicense -l "AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial" -s=only -v -c "Defense Unicorns" src/pepr/operator/crd/generated
+          addlicense -l "AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial" -s=only -v -c "Defense Unicorns" src/pepr/uds-cluster-crds/templates
 
       - task: gen-docs
 
